[[redirects]]
  from = "/*"
  to = "/"
  status = 200
[context.production]
  environment = { NODE_VERSION = "14" }
[context.deploy-preview]
  environment = { NODE_VERSION = "14" }
[context.branch-deploy]
  environment = { NODE_VERSION = "14" }